// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionTracker.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace CoreCover.Framework {
  public static partial class ExecutionTracker
  {
    static readonly string __ServiceName = "CoreCover.Framework.ExecutionTracker";

    static readonly grpc::Marshaller<global::CoreCover.Framework.ExecutedLine> __Marshaller_ExecutedLine = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CoreCover.Framework.ExecutedLine.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CoreCover.Framework.ExecutedLineReply> __Marshaller_ExecutedLineReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CoreCover.Framework.ExecutedLineReply.Parser.ParseFrom);

    static readonly grpc::Method<global::CoreCover.Framework.ExecutedLine, global::CoreCover.Framework.ExecutedLineReply> __Method_Track = new grpc::Method<global::CoreCover.Framework.ExecutedLine, global::CoreCover.Framework.ExecutedLineReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Track",
        __Marshaller_ExecutedLine,
        __Marshaller_ExecutedLineReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::CoreCover.Framework.ExecutionTrackerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ExecutionTracker</summary>
    public abstract partial class ExecutionTrackerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::CoreCover.Framework.ExecutedLineReply> Track(global::CoreCover.Framework.ExecutedLine request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ExecutionTracker</summary>
    public partial class ExecutionTrackerClient : grpc::ClientBase<ExecutionTrackerClient>
    {
      /// <summary>Creates a new client for ExecutionTracker</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ExecutionTrackerClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ExecutionTracker that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ExecutionTrackerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ExecutionTrackerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ExecutionTrackerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::CoreCover.Framework.ExecutedLineReply Track(global::CoreCover.Framework.ExecutedLine request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Track(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::CoreCover.Framework.ExecutedLineReply Track(global::CoreCover.Framework.ExecutedLine request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Track, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::CoreCover.Framework.ExecutedLineReply> TrackAsync(global::CoreCover.Framework.ExecutedLine request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TrackAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::CoreCover.Framework.ExecutedLineReply> TrackAsync(global::CoreCover.Framework.ExecutedLine request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Track, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ExecutionTrackerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ExecutionTrackerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ExecutionTrackerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Track, serviceImpl.Track).Build();
    }

  }
}
#endregion
