// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutionTracker.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CoreCover.Framework {

  /// <summary>Holder for reflection information generated from ExecutionTracker.proto</summary>
  public static partial class ExecutionTrackerReflection {

    #region Descriptor
    /// <summary>File descriptor for ExecutionTracker.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExecutionTrackerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZFeGVjdXRpb25UcmFja2VyLnByb3RvEhNDb3JlQ292ZXIuRnJhbWV3b3Jr",
            "ImoKDEV4ZWN1dGVkTGluZRISCgptb2R1bGVIYXNoGAEgASgJEhYKDW1ldGFk",
            "YXRhVG9rZW4Y1wggASgFEhcKD3N0YXJ0TGluZU51bWJlchgKIAEoBRIVCg1l",
            "bmRMaW5lTnVtYmVyGAwgASgFIhMKEUV4ZWN1dGVkTGluZVJlcGx5MmgKEEV4",
            "ZWN1dGlvblRyYWNrZXISVAoFVHJhY2sSIS5Db3JlQ292ZXIuRnJhbWV3b3Jr",
            "LkV4ZWN1dGVkTGluZRomLkNvcmVDb3Zlci5GcmFtZXdvcmsuRXhlY3V0ZWRM",
            "aW5lUmVwbHkiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreCover.Framework.ExecutedLine), global::CoreCover.Framework.ExecutedLine.Parser, new[]{ "ModuleHash", "MetadataToken", "StartLineNumber", "EndLineNumber" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CoreCover.Framework.ExecutedLineReply), global::CoreCover.Framework.ExecutedLineReply.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ExecutedLine : pb::IMessage<ExecutedLine> {
    private static readonly pb::MessageParser<ExecutedLine> _parser = new pb::MessageParser<ExecutedLine>(() => new ExecutedLine());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExecutedLine> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreCover.Framework.ExecutionTrackerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutedLine() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutedLine(ExecutedLine other) : this() {
      moduleHash_ = other.moduleHash_;
      metadataToken_ = other.metadataToken_;
      startLineNumber_ = other.startLineNumber_;
      endLineNumber_ = other.endLineNumber_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutedLine Clone() {
      return new ExecutedLine(this);
    }

    /// <summary>Field number for the "moduleHash" field.</summary>
    public const int ModuleHashFieldNumber = 1;
    private string moduleHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ModuleHash {
      get { return moduleHash_; }
      set {
        moduleHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metadataToken" field.</summary>
    public const int MetadataTokenFieldNumber = 1111;
    private int metadataToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MetadataToken {
      get { return metadataToken_; }
      set {
        metadataToken_ = value;
      }
    }

    /// <summary>Field number for the "startLineNumber" field.</summary>
    public const int StartLineNumberFieldNumber = 10;
    private int startLineNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartLineNumber {
      get { return startLineNumber_; }
      set {
        startLineNumber_ = value;
      }
    }

    /// <summary>Field number for the "endLineNumber" field.</summary>
    public const int EndLineNumberFieldNumber = 12;
    private int endLineNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EndLineNumber {
      get { return endLineNumber_; }
      set {
        endLineNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExecutedLine);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExecutedLine other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ModuleHash != other.ModuleHash) return false;
      if (MetadataToken != other.MetadataToken) return false;
      if (StartLineNumber != other.StartLineNumber) return false;
      if (EndLineNumber != other.EndLineNumber) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ModuleHash.Length != 0) hash ^= ModuleHash.GetHashCode();
      if (MetadataToken != 0) hash ^= MetadataToken.GetHashCode();
      if (StartLineNumber != 0) hash ^= StartLineNumber.GetHashCode();
      if (EndLineNumber != 0) hash ^= EndLineNumber.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ModuleHash.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ModuleHash);
      }
      if (StartLineNumber != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(StartLineNumber);
      }
      if (EndLineNumber != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(EndLineNumber);
      }
      if (MetadataToken != 0) {
        output.WriteRawTag(184, 69);
        output.WriteInt32(MetadataToken);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ModuleHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModuleHash);
      }
      if (MetadataToken != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MetadataToken);
      }
      if (StartLineNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartLineNumber);
      }
      if (EndLineNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndLineNumber);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExecutedLine other) {
      if (other == null) {
        return;
      }
      if (other.ModuleHash.Length != 0) {
        ModuleHash = other.ModuleHash;
      }
      if (other.MetadataToken != 0) {
        MetadataToken = other.MetadataToken;
      }
      if (other.StartLineNumber != 0) {
        StartLineNumber = other.StartLineNumber;
      }
      if (other.EndLineNumber != 0) {
        EndLineNumber = other.EndLineNumber;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ModuleHash = input.ReadString();
            break;
          }
          case 80: {
            StartLineNumber = input.ReadInt32();
            break;
          }
          case 96: {
            EndLineNumber = input.ReadInt32();
            break;
          }
          case 8888: {
            MetadataToken = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ExecutedLineReply : pb::IMessage<ExecutedLineReply> {
    private static readonly pb::MessageParser<ExecutedLineReply> _parser = new pb::MessageParser<ExecutedLineReply>(() => new ExecutedLineReply());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ExecutedLineReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CoreCover.Framework.ExecutionTrackerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutedLineReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutedLineReply(ExecutedLineReply other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ExecutedLineReply Clone() {
      return new ExecutedLineReply(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ExecutedLineReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ExecutedLineReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ExecutedLineReply other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
